05:02:08.514 PM	*******************Error start*******************
05:02:08.516 PM	(Exception Reference Id: f6d64c48-1f05-4ad9-8be1-935cb6d088e2)
Exception Message: Could not connect to net.tcp://localhost:9070/srvDBCache. The connection attempt lasted for a time span of 00:00:04.0910855. TCP error code 10061: No connection could be made because the target machine actively refused it 127.0.0.1:9070. 
Exception Information Source: mscorlib
Exception Information StackTrace: 
Server stack trace: 
   at System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   at System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Sagitec.Interface.IDBCache.GetDBSystemManagement(IDbConnection aconFramework, String astrApplicationName)
   at Sagitec.MVVMClient.AccountControllerBase.GetSystemManagementInfoFromThread()
Exception Information Target: HandleReturnMessage
----------********** Inner Exception **********---------- 
InnerException Message: No connection could be made because the target machine actively refused it 127.0.0.1:9070
InnerException Information Source: System
InnerException Information StackTrace:    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
Exception Information Target: DoConnect
****************************************************************************************************

05:02:08.519 PM	*******************Error End*******************
05:02:16.666 PM	*******************Error start*******************
05:02:16.668 PM	(Exception Reference Id: b0b98caf-4bce-4a53-9f63-9a46f83aa4d9)
Exception Message: Could not connect to net.tcp://localhost:9070/srvDBCache. The connection attempt lasted for a time span of 00:00:04.0639994. TCP error code 10061: No connection could be made because the target machine actively refused it 127.0.0.1:9070. 
Exception Information Source: mscorlib
Exception Information StackTrace: 
Server stack trace: 
   at System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   at System.ServiceModel.Channels.BufferedConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Sagitec.Interface.IDBCache.GetDBSystemManagement(IDbConnection aconFramework, String astrApplicationName)
   at Sagitec.MVVMClient.AccountControllerBase.GetSystemManagementInfoFromThread()
Exception Information Target: HandleReturnMessage
----------********** Inner Exception **********---------- 
InnerException Message: No connection could be made because the target machine actively refused it 127.0.0.1:9070
InnerException Information Source: System
InnerException Information StackTrace:    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.ServiceModel.Channels.SocketConnectionInitiator.Connect(Uri uri, TimeSpan timeout)
Exception Information Target: DoConnect
****************************************************************************************************

05:02:16.669 PM	*******************Error End*******************
05:02:21.076 PM	*******************Error start*******************
05:02:21.077 PM	(Exception Reference Id: 2b1da6bd-578b-4467-8da8-4e31272e88f7)
Exception Message: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.
Exception Information Source: mscorlib
Requested URL: http://localhost/OPUS/api/Neo/GetFormForOpen?astrFormID=wfmPayeeAccountMaintenance&StartTime=2025-04-09%2000:01:51.437&TransactionID=b79be0d5-33dd-6710-e653-4c6f538370fe&SenderID=FromMenu&SenderForm=wfmPayeeAccountLookup&Action=&SenderKey=&EncryptedControls=SrPyd8lJuag8mStEQProy6aREqzlc2zf%2bDUCcQZuRu4%3d%23%7e%23%7e%23%7eI8g7EsC3lxv1X9oIdyRWNQHK0ZPTv%2fxzMROCnD5diY1%2bGbJ4h0e13U08lG%2fVDhF8fHg6l688Io%2fkNIp15R1W1A%3d%3d
Exception Information StackTrace: 
Server stack trace: 
   at System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Sagitec.Interface.IMetaDataCache.ResetFormAttributeCache(String astrForm)
   at Sagitec.MVVMClient.utlFormCacheClient.Reset()
   at Sagitec.MVVMClient.utlFormCacheClient.IsLoaded()
   at Sagitec.MVVMClient.RequestValidation.CheckSecurityWebServer(Dictionary`2 adictParams, String astrAction, srvServers asrvServers, String& astrErrorMessage, String& astrAccessDeniedMessage)
   at Sagitec.MVVMClient.RequestValidation.ValidateSession(String astrController, String astrAction, String astrSenderID, String astrSenderForm, Dictionary`2 adictParams, srvServers asrvServers, MVVMSession aobjSessionData, String& astrErrorMessage, ArrayList& aarrNavigationParams, String& astrAccessDeniedMessage)
Exception Information Target: HandleReturnMessage

05:02:21.078 PM	*******************Error End*******************
05:03:34.191 PM	(Exception Reference Id: d5ce9b19-f4df-4a68-8f28-162561352b1d)
Exception Message: InitializeMVVMClient : Unable to connect to server at address net.tcp://localhost:9070/{0}, following error occurred Please wait Business Tier is getting refreshed.
Exception Information Source: 
Requested URL: http://localhost/OPUS/account/login
Exception Information StackTrace: 

05:03:34.202 PM	(Exception Reference Id: 7aa86d67-8d77-456a-91e9-14a8ba29fc29)
Exception Message: InitializeMVVMClient : Unable to connect to server at address net.tcp://localhost:9070/{0}, following error occurred Please wait Business Tier is getting refreshed.
Exception Information Source: 
Requested URL: http://localhost/OPUS/account/login
Exception Information StackTrace: 

